version: '3'

services:
  etcd:
    image: 'bitnami/etcd:latest'
    container_name: etcd
    # restart: always
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - '12379:2379'

  ipfs:
    container_name: ipfs
    image: 'ipfs/go-ipfs:latest'
    restart: always
    ports:
      - "7001:4001"
      - "8480:8080"
      - "5001:5001"

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123456'
      MYSQL_DATABASE: 'zut'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'

  nats:
    image: nats
    container_name: nats
    ports:
      - "4222:4222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
