// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: did_resolver.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDIDReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Did     string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Created string `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
}

func (x *CreateDIDReply) Reset() {
	*x = CreateDIDReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_did_resolver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDIDReply) ProtoMessage() {}

func (x *CreateDIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_did_resolver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDIDReply.ProtoReflect.Descriptor instead.
func (*CreateDIDReply) Descriptor() ([]byte, []int) {
	return file_did_resolver_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDIDReply) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *CreateDIDReply) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

type RevokeDIDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
}

func (x *RevokeDIDReq) Reset() {
	*x = RevokeDIDReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_did_resolver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevokeDIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeDIDReq) ProtoMessage() {}

func (x *RevokeDIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_did_resolver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeDIDReq.ProtoReflect.Descriptor instead.
func (*RevokeDIDReq) Descriptor() ([]byte, []int) {
	return file_did_resolver_proto_rawDescGZIP(), []int{1}
}

func (x *RevokeDIDReq) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

type GetDIDsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dids []*GetDIDItem `protobuf:"bytes,1,rep,name=dids,proto3" json:"dids,omitempty"`
}

func (x *GetDIDsReply) Reset() {
	*x = GetDIDsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_did_resolver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDIDsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDIDsReply) ProtoMessage() {}

func (x *GetDIDsReply) ProtoReflect() protoreflect.Message {
	mi := &file_did_resolver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDIDsReply.ProtoReflect.Descriptor instead.
func (*GetDIDsReply) Descriptor() ([]byte, []int) {
	return file_did_resolver_proto_rawDescGZIP(), []int{2}
}

func (x *GetDIDsReply) GetDids() []*GetDIDItem {
	if x != nil {
		return x.Dids
	}
	return nil
}

type GetDIDItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Did     string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Created string `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
}

func (x *GetDIDItem) Reset() {
	*x = GetDIDItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_did_resolver_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDIDItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDIDItem) ProtoMessage() {}

func (x *GetDIDItem) ProtoReflect() protoreflect.Message {
	mi := &file_did_resolver_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDIDItem.ProtoReflect.Descriptor instead.
func (*GetDIDItem) Descriptor() ([]byte, []int) {
	return file_did_resolver_proto_rawDescGZIP(), []int{3}
}

func (x *GetDIDItem) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *GetDIDItem) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

type GetDIDDocumentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
}

func (x *GetDIDDocumentReq) Reset() {
	*x = GetDIDDocumentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_did_resolver_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDIDDocumentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDIDDocumentReq) ProtoMessage() {}

func (x *GetDIDDocumentReq) ProtoReflect() protoreflect.Message {
	mi := &file_did_resolver_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDIDDocumentReq.ProtoReflect.Descriptor instead.
func (*GetDIDDocumentReq) Descriptor() ([]byte, []int) {
	return file_did_resolver_proto_rawDescGZIP(), []int{4}
}

func (x *GetDIDDocumentReq) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

type GetDIDDocumentRely struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DidDocument *DIDDocument `protobuf:"bytes,1,opt,name=did_document,json=didDocument,proto3" json:"did_document,omitempty"`
}

func (x *GetDIDDocumentRely) Reset() {
	*x = GetDIDDocumentRely{}
	if protoimpl.UnsafeEnabled {
		mi := &file_did_resolver_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDIDDocumentRely) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDIDDocumentRely) ProtoMessage() {}

func (x *GetDIDDocumentRely) ProtoReflect() protoreflect.Message {
	mi := &file_did_resolver_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDIDDocumentRely.ProtoReflect.Descriptor instead.
func (*GetDIDDocumentRely) Descriptor() ([]byte, []int) {
	return file_did_resolver_proto_rawDescGZIP(), []int{5}
}

func (x *GetDIDDocumentRely) GetDidDocument() *DIDDocument {
	if x != nil {
		return x.DidDocument
	}
	return nil
}

type DIDDocument struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Context        []string                 `protobuf:"bytes,1,rep,name=context,proto3" json:"context,omitempty"` // [json_name = "@context"];
	Id             string                   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Version        int32                    `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Created        string                   `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	Updated        string                   `protobuf:"bytes,5,opt,name=updated,proto3" json:"updated,omitempty"`
	PublicKey      []*DIDDocument_PublicKey `protobuf:"bytes,6,rep,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Authentication []string                 `protobuf:"bytes,7,rep,name=authentication,proto3" json:"authentication,omitempty"`
	Proof          *DIDDocument_Proof       `protobuf:"bytes,8,opt,name=proof,proto3" json:"proof,omitempty"`
}

func (x *DIDDocument) Reset() {
	*x = DIDDocument{}
	if protoimpl.UnsafeEnabled {
		mi := &file_did_resolver_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DIDDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DIDDocument) ProtoMessage() {}

func (x *DIDDocument) ProtoReflect() protoreflect.Message {
	mi := &file_did_resolver_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DIDDocument.ProtoReflect.Descriptor instead.
func (*DIDDocument) Descriptor() ([]byte, []int) {
	return file_did_resolver_proto_rawDescGZIP(), []int{6}
}

func (x *DIDDocument) GetContext() []string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *DIDDocument) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DIDDocument) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DIDDocument) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *DIDDocument) GetUpdated() string {
	if x != nil {
		return x.Updated
	}
	return ""
}

func (x *DIDDocument) GetPublicKey() []*DIDDocument_PublicKey {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *DIDDocument) GetAuthentication() []string {
	if x != nil {
		return x.Authentication
	}
	return nil
}

func (x *DIDDocument) GetProof() *DIDDocument_Proof {
	if x != nil {
		return x.Proof
	}
	return nil
}

type GetPublicKeyByDIDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
}

func (x *GetPublicKeyByDIDReq) Reset() {
	*x = GetPublicKeyByDIDReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_did_resolver_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPublicKeyByDIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeyByDIDReq) ProtoMessage() {}

func (x *GetPublicKeyByDIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_did_resolver_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeyByDIDReq.ProtoReflect.Descriptor instead.
func (*GetPublicKeyByDIDReq) Descriptor() ([]byte, []int) {
	return file_did_resolver_proto_rawDescGZIP(), []int{7}
}

func (x *GetPublicKeyByDIDReq) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

type GetPublicKeyByDIDReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey string `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (x *GetPublicKeyByDIDReply) Reset() {
	*x = GetPublicKeyByDIDReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_did_resolver_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPublicKeyByDIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeyByDIDReply) ProtoMessage() {}

func (x *GetPublicKeyByDIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_did_resolver_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeyByDIDReply.ProtoReflect.Descriptor instead.
func (*GetPublicKeyByDIDReply) Descriptor() ([]byte, []int) {
	return file_did_resolver_proto_rawDescGZIP(), []int{8}
}

func (x *GetPublicKeyByDIDReply) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type ExistDIDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid int64  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Did string `protobuf:"bytes,2,opt,name=did,proto3" json:"did,omitempty"`
}

func (x *ExistDIDReq) Reset() {
	*x = ExistDIDReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_did_resolver_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExistDIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistDIDReq) ProtoMessage() {}

func (x *ExistDIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_did_resolver_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistDIDReq.ProtoReflect.Descriptor instead.
func (*ExistDIDReq) Descriptor() ([]byte, []int) {
	return file_did_resolver_proto_rawDescGZIP(), []int{9}
}

func (x *ExistDIDReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ExistDIDReq) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

type ExistDIDReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exists bool `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
}

func (x *ExistDIDReply) Reset() {
	*x = ExistDIDReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_did_resolver_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExistDIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistDIDReply) ProtoMessage() {}

func (x *ExistDIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_did_resolver_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistDIDReply.ProtoReflect.Descriptor instead.
func (*ExistDIDReply) Descriptor() ([]byte, []int) {
	return file_did_resolver_proto_rawDescGZIP(), []int{10}
}

func (x *ExistDIDReply) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type GetOwnerByDIDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
}

func (x *GetOwnerByDIDReq) Reset() {
	*x = GetOwnerByDIDReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_did_resolver_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOwnerByDIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOwnerByDIDReq) ProtoMessage() {}

func (x *GetOwnerByDIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_did_resolver_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOwnerByDIDReq.ProtoReflect.Descriptor instead.
func (*GetOwnerByDIDReq) Descriptor() ([]byte, []int) {
	return file_did_resolver_proto_rawDescGZIP(), []int{11}
}

func (x *GetOwnerByDIDReq) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

type GetOwnerByDIDReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *GetOwnerByDIDReply) Reset() {
	*x = GetOwnerByDIDReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_did_resolver_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOwnerByDIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOwnerByDIDReply) ProtoMessage() {}

func (x *GetOwnerByDIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_did_resolver_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOwnerByDIDReply.ProtoReflect.Descriptor instead.
func (*GetOwnerByDIDReply) Descriptor() ([]byte, []int) {
	return file_did_resolver_proto_rawDescGZIP(), []int{12}
}

func (x *GetOwnerByDIDReply) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type DIDDocument_PublicKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type         string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	PublicKeyHex string `protobuf:"bytes,3,opt,name=public_key_hex,json=publicKeyHex,proto3" json:"public_key_hex,omitempty"`
}

func (x *DIDDocument_PublicKey) Reset() {
	*x = DIDDocument_PublicKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_did_resolver_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DIDDocument_PublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DIDDocument_PublicKey) ProtoMessage() {}

func (x *DIDDocument_PublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_did_resolver_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DIDDocument_PublicKey.ProtoReflect.Descriptor instead.
func (*DIDDocument_PublicKey) Descriptor() ([]byte, []int) {
	return file_did_resolver_proto_rawDescGZIP(), []int{6, 0}
}

func (x *DIDDocument_PublicKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DIDDocument_PublicKey) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DIDDocument_PublicKey) GetPublicKeyHex() string {
	if x != nil {
		return x.PublicKeyHex
	}
	return ""
}

type DIDDocument_Proof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Creator   string `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	Signature string `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *DIDDocument_Proof) Reset() {
	*x = DIDDocument_Proof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_did_resolver_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DIDDocument_Proof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DIDDocument_Proof) ProtoMessage() {}

func (x *DIDDocument_Proof) ProtoReflect() protoreflect.Message {
	mi := &file_did_resolver_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DIDDocument_Proof.ProtoReflect.Descriptor instead.
func (*DIDDocument_Proof) Descriptor() ([]byte, []int) {
	return file_did_resolver_proto_rawDescGZIP(), []int{6, 1}
}

func (x *DIDDocument_Proof) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DIDDocument_Proof) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *DIDDocument_Proof) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

var File_did_resolver_proto protoreflect.FileDescriptor

var file_did_resolver_proto_rawDesc = []byte{
	0x0a, 0x12, 0x64, 0x69, 0x64, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x3c, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x49, 0x44, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x64, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x22, 0x20, 0x0a,
	0x0c, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x44, 0x49, 0x44, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a,
	0x03, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69, 0x64, 0x22,
	0x2f, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x44, 0x49, 0x44, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x1f, 0x0a, 0x04, 0x64, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x47, 0x65, 0x74, 0x44, 0x49, 0x44, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x64, 0x69, 0x64, 0x73,
	0x22, 0x38, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x44, 0x49, 0x44, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x10,
	0x0a, 0x03, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x22, 0x25, 0x0a, 0x11, 0x47, 0x65,
	0x74, 0x44, 0x49, 0x44, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x10, 0x0a, 0x03, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69,
	0x64, 0x22, 0x45, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x44, 0x49, 0x44, 0x44, 0x6f, 0x63, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x6c, 0x79, 0x12, 0x2f, 0x0a, 0x0c, 0x64, 0x69, 0x64, 0x5f, 0x64,
	0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x44, 0x49, 0x44, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0b, 0x64, 0x69, 0x64,
	0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0xba, 0x03, 0x0a, 0x0b, 0x44, 0x49, 0x44,
	0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x78, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x12, 0x35, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x44, 0x49, 0x44, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x09, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x26, 0x0a, 0x0e, 0x61, 0x75, 0x74, 0x68, 0x65,
	0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x28, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x44, 0x49, 0x44, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x72, 0x6f,
	0x6f, 0x66, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x1a, 0x55, 0x0a, 0x09, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x68, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x48, 0x65, 0x78,
	0x1a, 0x53, 0x0a, 0x05, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x28, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x4b, 0x65, 0x79, 0x42, 0x79, 0x44, 0x49, 0x44, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a,
	0x03, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69, 0x64, 0x22,
	0x37, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x42,
	0x79, 0x44, 0x49, 0x44, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x22, 0x31, 0x0a, 0x0b, 0x45, 0x78, 0x69, 0x73,
	0x74, 0x44, 0x49, 0x44, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69, 0x64, 0x22, 0x27, 0x0a, 0x0d, 0x45,
	0x78, 0x69, 0x73, 0x74, 0x44, 0x49, 0x44, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x78,
	0x69, 0x73, 0x74, 0x73, 0x22, 0x24, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4f, 0x77, 0x6e, 0x65, 0x72,
	0x42, 0x79, 0x44, 0x49, 0x44, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69, 0x64, 0x22, 0x26, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x42, 0x79, 0x44, 0x49, 0x44, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x32, 0xd8, 0x04, 0x0a, 0x0b, 0x44, 0x49, 0x44, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76,
	0x65, 0x72, 0x12, 0x5a, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x49, 0x44, 0x12,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x44, 0x49, 0x44, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x24, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1e,
	0x22, 0x19, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x69, 0x64, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65,
	0x72, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x69, 0x64, 0x3a, 0x01, 0x2a, 0x12, 0x58,
	0x0a, 0x09, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x44, 0x49, 0x44, 0x12, 0x0d, 0x2e, 0x52, 0x65,
	0x76, 0x6f, 0x6b, 0x65, 0x44, 0x49, 0x44, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x24, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1e, 0x22, 0x19, 0x2f, 0x76, 0x31, 0x2f,
	0x64, 0x69, 0x64, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x2f, 0x72, 0x65, 0x76, 0x6f,
	0x6b, 0x65, 0x64, 0x69, 0x64, 0x3a, 0x01, 0x2a, 0x12, 0x51, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x44,
	0x49, 0x44, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0d, 0x2e, 0x47, 0x65,
	0x74, 0x44, 0x49, 0x44, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1f, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x19, 0x12, 0x17, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x69, 0x64, 0x72, 0x65, 0x73, 0x6f, 0x6c,
	0x76, 0x65, 0x72, 0x2f, 0x67, 0x65, 0x74, 0x64, 0x69, 0x64, 0x73, 0x12, 0x67, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x44, 0x49, 0x44, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x2e,
	0x47, 0x65, 0x74, 0x44, 0x49, 0x44, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x49, 0x44, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x6c, 0x79, 0x22, 0x2c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x26, 0x12, 0x24,
	0x2f, 0x76, 0x31, 0x2f, 0x64, 0x69, 0x64, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x2f,
	0x67, 0x65, 0x74, 0x64, 0x69, 0x64, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x7b,
	0x64, 0x69, 0x64, 0x7d, 0x12, 0x74, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x4b, 0x65, 0x79, 0x42, 0x79, 0x44, 0x49, 0x44, 0x12, 0x15, 0x2e, 0x47, 0x65, 0x74, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x42, 0x79, 0x44, 0x49, 0x44, 0x52, 0x65, 0x71,
	0x1a, 0x17, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x42,
	0x79, 0x44, 0x49, 0x44, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2f, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x29, 0x12, 0x27, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x69, 0x64, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76,
	0x65, 0x72, 0x2f, 0x67, 0x65, 0x74, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x6b, 0x65, 0x79, 0x62,
	0x79, 0x64, 0x69, 0x64, 0x2f, 0x7b, 0x64, 0x69, 0x64, 0x7d, 0x12, 0x28, 0x0a, 0x08, 0x45, 0x78,
	0x69, 0x73, 0x74, 0x44, 0x49, 0x44, 0x12, 0x0c, 0x2e, 0x45, 0x78, 0x69, 0x73, 0x74, 0x44, 0x49,
	0x44, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x45, 0x78, 0x69, 0x73, 0x74, 0x44, 0x49, 0x44, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x37, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4f, 0x77, 0x6e, 0x65, 0x72,
	0x42, 0x79, 0x44, 0x49, 0x44, 0x12, 0x11, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x77, 0x6e, 0x65, 0x72,
	0x42, 0x79, 0x44, 0x49, 0x44, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x77,
	0x6e, 0x65, 0x72, 0x42, 0x79, 0x44, 0x49, 0x44, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x06, 0x5a,
	0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_did_resolver_proto_rawDescOnce sync.Once
	file_did_resolver_proto_rawDescData = file_did_resolver_proto_rawDesc
)

func file_did_resolver_proto_rawDescGZIP() []byte {
	file_did_resolver_proto_rawDescOnce.Do(func() {
		file_did_resolver_proto_rawDescData = protoimpl.X.CompressGZIP(file_did_resolver_proto_rawDescData)
	})
	return file_did_resolver_proto_rawDescData
}

var file_did_resolver_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_did_resolver_proto_goTypes = []interface{}{
	(*CreateDIDReply)(nil),         // 0: CreateDIDReply
	(*RevokeDIDReq)(nil),           // 1: RevokeDIDReq
	(*GetDIDsReply)(nil),           // 2: GetDIDsReply
	(*GetDIDItem)(nil),             // 3: GetDIDItem
	(*GetDIDDocumentReq)(nil),      // 4: GetDIDDocumentReq
	(*GetDIDDocumentRely)(nil),     // 5: GetDIDDocumentRely
	(*DIDDocument)(nil),            // 6: DIDDocument
	(*GetPublicKeyByDIDReq)(nil),   // 7: GetPublicKeyByDIDReq
	(*GetPublicKeyByDIDReply)(nil), // 8: GetPublicKeyByDIDReply
	(*ExistDIDReq)(nil),            // 9: ExistDIDReq
	(*ExistDIDReply)(nil),          // 10: ExistDIDReply
	(*GetOwnerByDIDReq)(nil),       // 11: GetOwnerByDIDReq
	(*GetOwnerByDIDReply)(nil),     // 12: GetOwnerByDIDReply
	(*DIDDocument_PublicKey)(nil),  // 13: DIDDocument.PublicKey
	(*DIDDocument_Proof)(nil),      // 14: DIDDocument.Proof
	(*emptypb.Empty)(nil),          // 15: google.protobuf.Empty
}
var file_did_resolver_proto_depIdxs = []int32{
	3,  // 0: GetDIDsReply.dids:type_name -> GetDIDItem
	6,  // 1: GetDIDDocumentRely.did_document:type_name -> DIDDocument
	13, // 2: DIDDocument.public_key:type_name -> DIDDocument.PublicKey
	14, // 3: DIDDocument.proof:type_name -> DIDDocument.Proof
	15, // 4: DIDResolver.CreateDID:input_type -> google.protobuf.Empty
	1,  // 5: DIDResolver.RevokeDID:input_type -> RevokeDIDReq
	15, // 6: DIDResolver.GetDIDs:input_type -> google.protobuf.Empty
	4,  // 7: DIDResolver.GetDIDDocument:input_type -> GetDIDDocumentReq
	7,  // 8: DIDResolver.GetPublicKeyByDID:input_type -> GetPublicKeyByDIDReq
	9,  // 9: DIDResolver.ExistDID:input_type -> ExistDIDReq
	11, // 10: DIDResolver.GetOwnerByDID:input_type -> GetOwnerByDIDReq
	0,  // 11: DIDResolver.CreateDID:output_type -> CreateDIDReply
	15, // 12: DIDResolver.RevokeDID:output_type -> google.protobuf.Empty
	2,  // 13: DIDResolver.GetDIDs:output_type -> GetDIDsReply
	5,  // 14: DIDResolver.GetDIDDocument:output_type -> GetDIDDocumentRely
	8,  // 15: DIDResolver.GetPublicKeyByDID:output_type -> GetPublicKeyByDIDReply
	10, // 16: DIDResolver.ExistDID:output_type -> ExistDIDReply
	12, // 17: DIDResolver.GetOwnerByDID:output_type -> GetOwnerByDIDReply
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_did_resolver_proto_init() }
func file_did_resolver_proto_init() {
	if File_did_resolver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_did_resolver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDIDReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_did_resolver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevokeDIDReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_did_resolver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDIDsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_did_resolver_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDIDItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_did_resolver_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDIDDocumentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_did_resolver_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDIDDocumentRely); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_did_resolver_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DIDDocument); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_did_resolver_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPublicKeyByDIDReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_did_resolver_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPublicKeyByDIDReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_did_resolver_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExistDIDReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_did_resolver_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExistDIDReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_did_resolver_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOwnerByDIDReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_did_resolver_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOwnerByDIDReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_did_resolver_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DIDDocument_PublicKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_did_resolver_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DIDDocument_Proof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_did_resolver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_did_resolver_proto_goTypes,
		DependencyIndexes: file_did_resolver_proto_depIdxs,
		MessageInfos:      file_did_resolver_proto_msgTypes,
	}.Build()
	File_did_resolver_proto = out.File
	file_did_resolver_proto_rawDesc = nil
	file_did_resolver_proto_goTypes = nil
	file_did_resolver_proto_depIdxs = nil
}
