
[Network]
#type rpc or channel
Type="channel"
CAFile="../fisco/nodes/127.0.0.1/sdk/ca.crt"
Cert="../fisco/nodes/127.0.0.1/sdk/sdk.crt"
Key="../fisco/nodes/127.0.0.1/sdk/sdk.key"
[[Network.Connection]]
NodeURL="127.0.0.1:20200"
GroupID=1
# [[Network.Connection]]
# NodeURL="127.0.0.1:20200"
# GroupID=2

[Account]
# only support PEM format for now
KeyFile="../fisco/client/.ci/0x83309d045a19c44dc3722d15a6abd472f95866ac.pem"

[Chain]
ChainID=1
SMCrypto=false

[log]
Path="./"
